name: Build and Publish

on:
  push:
    tags:
      - 'v*.*.*'
jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Verify .NET Framework 4.8
      run: |
        if (!(Test-Path "C:\Windows\Microsoft.NET\Framework\v4.0.30319")) {
          Write-Error ".NET Framework 4.8 is not installed"
          exit 1
        }

    - name: Restore dependencies
      run: dotnet restore

    - name: Print working directory
      run: pwd

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Print working directory
      run: pwd

    - name: List current directory before pack
      run: dir

    - name: Pack
      run: dotnet pack --configuration Release --no-restore --include-symbols --include-source --output ./artifacts
      
    - name: Wait for file system to update
      run: timeout 5

    - name: Print working directory
      run: pwd
      
    - name: List artifacts directory
      run: dir ./artifacts

    - name: Publish to GitHub Packages
      run: dotnet nuget push './artifacts/*.nupkg' --source https://nuget.pkg.github.com/RenPsg/index.json --api-key ${{ secrets.GITHUB_TOKEN }}
